"""Remove department_uid column

Revision ID: a7349ad3f525
Revises: 0bfbc263d542
Create Date: 2021-10-30 21:26:12.021304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7349ad3f525'
down_revision = '0bfbc263d542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'department_uid')
    op.drop_index('idx_initiatives_locate', table_name='initiatives')
    op.drop_index('idx_map_objects_point', table_name='map_objects')
    op.drop_index('idx_marker_histories_coords', table_name='marker_histories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_marker_histories_coords', 'marker_histories', ['coords'], unique=False)
    op.create_index('idx_map_objects_point', 'map_objects', ['point'], unique=False)
    op.create_index('idx_initiatives_locate', 'initiatives', ['locate'], unique=False)
    op.add_column('departments', sa.Column('department_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
