"""empty message

Revision ID: cc9aec99178c
Revises: a7349ad3f525
Create Date: 2021-11-14 23:28:47.750753

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cc9aec99178c'
down_revision = 'a7349ad3f525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appeal_chats_appeal_id_fkey', 'appeal_chats', type_='foreignkey')
    op.create_foreign_key(None, 'appeal_chats', 'user_appeals', ['appeal_id'], ['id'], ondelete='CASCADE')
    op.add_column('appeal_history_attachments', sa.Column('appeal_history_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appeal_history_attachments', 'appeal_history', ['appeal_history_id'], ['id'])
    op.drop_constraint('appeal_users_employee_id_fkey', 'appeal_users', type_='foreignkey')
    op.create_foreign_key(None, 'appeal_users', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appeal_users', type_='foreignkey')
    op.create_foreign_key('appeal_users_employee_id_fkey', 'appeal_users', 'employees', ['employee_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_constraint(None, 'appeal_history_attachments', type_='foreignkey')
    op.drop_column('appeal_history_attachments', 'appeal_history_id')
    op.drop_constraint(None, 'appeal_chats', type_='foreignkey')
    op.create_foreign_key('appeal_chats_appeal_id_fkey', 'appeal_chats', 'users', ['appeal_id'], ['id'],
                          ondelete='CASCADE')
    # ### end Alembic commands ###
