"""empty message

Revision ID: fa4139854ead
Revises: f7dd3dab7ff7
Create Date: 2021-11-21 14:51:03.496649

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fa4139854ead'
down_revision = 'f7dd3dab7ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_appeal_attachments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_appeal_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['attachments.id'], ),
                    sa.ForeignKeyConstraint(['user_appeal_id'], ['user_appeals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_appeal_attachments')
    # ### end Alembic commands ###
